apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgdata
  namespace: openproject
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: openproject
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: environment
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: pgdata
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: pgdata
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: openproject
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
  - port: 5432
    nodePort: 30431
