apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: openproject
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: openproject/community:12
        args:
        - ./docker/prod/worker
        envFrom:
        - secretRef:
            name: environment
        volumeMounts:
          - mountPath: /var/openproject/assets
            name: opdata
      volumes:
        - name: opdata
          persistentVolumeClaim:
            claimName: opdata
